<?php
namespace app\World\Object;

/**
 * 对象字段值
 */
class UpdateObjectFields
{
    const Schools = [
        'SPELL_SCHOOL_NORMAL' => 0,
        'SPELL_SCHOOL_HOLY'   => 1,
        'SPELL_SCHOOL_FIRE'   => 2,
        'SPELL_SCHOOL_NATURE' => 3,
        'SPELL_SCHOOL_FROST'  => 4,
        'SPELL_SCHOOL_SHADOW' => 5,
        'SPELL_SCHOOL_ARCANE' => 6,
    ];

    const ObjectField = [
        'GUID'    => 0x0000, #Size:2,Type:LONG,Flags:PUBLIC
        'TYPE'    => 0x0002, #Size:1,Type:INT,Flags:PUBLIC
        'ENTRY'   => 0x0003, #Size:1,Type:INT,Flags:PUBLIC
        'SCALE_X' => 0x0004, #Size:1,Type:FLOAT,Flags:PUBLIC
        'PADDING' => 0x0005, #Size:1,Type:INT,Flags:NONE
        'END'     => 0x0006,
    ];

    const ItemField = [
        'OWNER'                => self::ObjectField['END'] + 0x0000, #Size:2,Type:LONG,Flags:PUBLIC
        'CONTAINED'            => self::ObjectField['END'] + 0x0002, #Size:2,Type:LONG,Flags:PUBLIC
        'CREATOR'              => self::ObjectField['END'] + 0x0004, #Size:2,Type:LONG,Flags:PUBLIC
        'GIFTCREATOR'          => self::ObjectField['END'] + 0x0006, #Size:2,Type:LONG,Flags:PUBLIC
        'STACK_COUNT'          => self::ObjectField['END'] + 0x0008, #Size:1,Type:INT,Flags:OWNER_ONLY,UNK2
        'DURATION'             => self::ObjectField['END'] + 0x0009, #Size:1,Type:INT,Flags:OWNER_ONLY,UNK2
        'SPELL_CHARGES'        => self::ObjectField['END'] + 0x000A, #Size:5,Type:INT,Flags:OWNER_ONLY,UNK2
        'FLAGS'                => self::ObjectField['END'] + 0x000F, #Size:1,Type:INT,Flags:PUBLIC
        'ENCHANTMENT'          => self::ObjectField['END'] + 0x0010, #Size:33,Type:INT,Flags:PUBLIC
        'PROPERTY_SEED'        => self::ObjectField['END'] + 0x0031, #Size:1,Type:INT,Flags:PUBLIC
        'RANDOM_PROPERTIES_ID' => self::ObjectField['END'] + 0x0032, #Size:1,Type:INT,Flags:PUBLIC
        'ITEM_TEXT_ID'         => self::ObjectField['END'] + 0x0033, #Size:1,Type:INT,Flags:OWNER_ONLY
        'DURABILITY'           => self::ObjectField['END'] + 0x0034, #Size:1,Type:INT,Flags:OWNER_ONLY,UNK2
        'MAXDURABILITY'        => self::ObjectField['END'] + 0x0035, #Size:1,Type:INT,Flags:OWNER_ONLY,UNK2
        'END'                  => self::ObjectField['END'] + 0x0036,
    ];

    const ContainerField = [
        'NUM_SLOTS' => self::ItemField['END'] + 0x0000, #Size:1,Type:INT,Flags:PUBLIC
        'ALIGN_PAD' => self::ItemField['END'] + 0x0001, #Size:1,Type:BYTES,Flags:NONE
        'SLOT_1'    => self::ItemField['END'] + 0x0002, #Size:72,Type:LONG,Flags:PUBLIC
        'END'       => self::ItemField['END'] + 0x004A,
    ];

    const UnitField = [
        'CHARM'                          => self::ObjectField['END'] + 0x0000, #Size:2,Type:LONG,Flags:PUBLIC
        'SUMMON'                         => self::ObjectField['END'] + 0x0002, #Size:2,Type:LONG,Flags:PUBLIC
        'CHARMEDBY'                      => self::ObjectField['END'] + 0x0004, #Size:2,Type:LONG,Flags:PUBLIC
        'SUMMONEDBY'                     => self::ObjectField['END'] + 0x0006, #Size:2,Type:LONG,Flags:PUBLIC
        'CREATEDBY'                      => self::ObjectField['END'] + 0x0008, #Size:2,Type:LONG,Flags:PUBLIC
        'TARGET'                         => self::ObjectField['END'] + 0x000A, #Size:2,Type:LONG,Flags:PUBLIC
        'PERSUADED'                      => self::ObjectField['END'] + 0x000C, #Size:2,Type:LONG,Flags:PUBLIC
        'CHANNEL_OBJECT'                 => self::ObjectField['END'] + 0x000E, #Size:2,Type:LONG,Flags:PUBLIC
        'HEALTH'                         => self::ObjectField['END'] + 0x0010, #Size:1,Type:INT,Flags:DYNAMIC
        'POWER1'                         => self::ObjectField['END'] + 0x0011, #Size:1,Type:INT,Flags:PUBLIC
        'POWER2'                         => self::ObjectField['END'] + 0x0012, #Size:1,Type:INT,Flags:PUBLIC
        'POWER3'                         => self::ObjectField['END'] + 0x0013, #Size:1,Type:INT,Flags:PUBLIC
        'POWER4'                         => self::ObjectField['END'] + 0x0014, #Size:1,Type:INT,Flags:PUBLIC
        'POWER5'                         => self::ObjectField['END'] + 0x0015, #Size:1,Type:INT,Flags:PUBLIC
        'MAXHEALTH'                      => self::ObjectField['END'] + 0x0016, #Size:1,Type:INT,Flags:DYNAMIC
        'MAXPOWER1'                      => self::ObjectField['END'] + 0x0017, #Size:1,Type:INT,Flags:PUBLIC
        'MAXPOWER2'                      => self::ObjectField['END'] + 0x0018, #Size:1,Type:INT,Flags:PUBLIC
        'MAXPOWER3'                      => self::ObjectField['END'] + 0x0019, #Size:1,Type:INT,Flags:PUBLIC
        'MAXPOWER4'                      => self::ObjectField['END'] + 0x001A, #Size:1,Type:INT,Flags:PUBLIC
        'MAXPOWER5'                      => self::ObjectField['END'] + 0x001B, #Size:1,Type:INT,Flags:PUBLIC
        'LEVEL'                          => self::ObjectField['END'] + 0x001C, #Size:1,Type:INT,Flags:PUBLIC
        'FACTIONTEMPLATE'                => self::ObjectField['END'] + 0x001D, #Size:1,Type:INT,Flags:PUBLIC
        'BYTES_0'                        => self::ObjectField['END'] + 0x001E, #Size:1,Type:BYTES,Flags:PUBLIC
        'VIRTUAL_ITEM_SLOT_DISPLAY'      => self::ObjectField['END'] + 0x001F, #Size:3,Type:INT,Flags:PUBLIC
        'VIRTUAL_ITEM_INFO'              => self::ObjectField['END'] + 0x0022, #Size:6,Type:BYTES,Flags:PUBLIC
        'FLAGS'                          => self::ObjectField['END'] + 0x0028, #Size:1,Type:INT,Flags:PUBLIC
        'FLAGS_2'                        => self::ObjectField['END'] + 0x0029, #Size:1,Type:INT,Flags:PUBLIC
        'AURA'                           => self::ObjectField['END'] + 0x002A, #Size:56,Type:INT,Flags:PUBLIC
        'AURAFLAGS'                      => self::ObjectField['END'] + 0x0062, #Size:14,Type:BYTES,Flags:PUBLIC
        'AURALEVELS'                     => self::ObjectField['END'] + 0x0070, #Size:14,Type:BYTES,Flags:PUBLIC
        'AURAAPPLICATIONS'               => self::ObjectField['END'] + 0x007E, #Size:14,Type:BYTES,Flags:PUBLIC
        'AURASTATE'                      => self::ObjectField['END'] + 0x008C, #Size:1,Type:INT,Flags:PUBLIC
        'BASEATTACKTIME'                 => self::ObjectField['END'] + 0x008D, #Size:1,Type:INT,Flags:PUBLIC
        'OFFHANDATTACKTIME'              => self::ObjectField['END'] + 0x008E, #Size:1,Type:INT,Flags:PUBLIC
        'RANGEDATTACKTIME'               => self::ObjectField['END'] + 0x008F, #Size:1,Type:INT,Flags:PRIVATE
        'BOUNDINGRADIUS'                 => self::ObjectField['END'] + 0x0090, #Size:1,Type:FLOAT,Flags:PUBLIC
        'COMBATREACH'                    => self::ObjectField['END'] + 0x0091, #Size:1,Type:FLOAT,Flags:PUBLIC
        'DISPLAYID'                      => self::ObjectField['END'] + 0x0092, #Size:1,Type:INT,Flags:PUBLIC
        'NATIVEDISPLAYID'                => self::ObjectField['END'] + 0x0093, #Size:1,Type:INT,Flags:PUBLIC
        'MOUNTDISPLAYID'                 => self::ObjectField['END'] + 0x0094, #Size:1,Type:INT,Flags:PUBLIC
        'MINDAMAGE'                      => self::ObjectField['END'] + 0x0095, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY,UNK3
        'MAXDAMAGE'                      => self::ObjectField['END'] + 0x0096, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY,UNK3
        'MINOFFHANDDAMAGE'               => self::ObjectField['END'] + 0x0097, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY,UNK3
        'MAXOFFHANDDAMAGE'               => self::ObjectField['END'] + 0x0098, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY,UNK3
        'BYTES_1'                        => self::ObjectField['END'] + 0x0099, #Size:1,Type:BYTES,Flags:PUBLIC
        'PETNUMBER'                      => self::ObjectField['END'] + 0x009A, #Size:1,Type:INT,Flags:PUBLIC
        'PET_NAME_TIMESTAMP'             => self::ObjectField['END'] + 0x009B, #Size:1,Type:INT,Flags:PUBLIC
        'PETEXPERIENCE'                  => self::ObjectField['END'] + 0x009C, #Size:1,Type:INT,Flags:OWNER_ONLY
        'PETNEXTLEVELEXP'                => self::ObjectField['END'] + 0x009D, #Size:1,Type:INT,Flags:OWNER_ONLY
        'DYNAMIC_FLAGS'                  => self::ObjectField['END'] + 0x009E, #Size:1,Type:INT,Flags:DYNAMIC
        'CHANNEL_SPELL'                  => self::ObjectField['END'] + 0x009F, #Size:1,Type:INT,Flags:PUBLIC
        'MOD_CAST_SPEED'                 => self::ObjectField['END'] + 0x00A0, #Size:1,Type:FLOAT,Flags:PUBLIC
        'CREATED_BY_SPELL'               => self::ObjectField['END'] + 0x00A1, #Size:1,Type:INT,Flags:PUBLIC
        'NPC_FLAGS'                      => self::ObjectField['END'] + 0x00A2, #Size:1,Type:INT,Flags:DYNAMIC
        'NPC_EMOTESTATE'                 => self::ObjectField['END'] + 0x00A3, #Size:1,Type:INT,Flags:PUBLIC
        'TRAINING_POINTS'                => self::ObjectField['END'] + 0x00A4, #Size:1,Type:TWO_SHORT,Flags:OWNER_ONLY
        'STAT0'                          => self::ObjectField['END'] + 0x00A5, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'STAT1'                          => self::ObjectField['END'] + 0x00A6, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'STAT2'                          => self::ObjectField['END'] + 0x00A7, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'STAT3'                          => self::ObjectField['END'] + 0x00A8, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'STAT4'                          => self::ObjectField['END'] + 0x00A9, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'POSSTAT0'                       => self::ObjectField['END'] + 0x00AA, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'POSSTAT1'                       => self::ObjectField['END'] + 0x00AB, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'POSSTAT2'                       => self::ObjectField['END'] + 0x00AC, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'POSSTAT3'                       => self::ObjectField['END'] + 0x00AD, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'POSSTAT4'                       => self::ObjectField['END'] + 0x00AE, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'NEGSTAT0'                       => self::ObjectField['END'] + 0x00AF, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'NEGSTAT1'                       => self::ObjectField['END'] + 0x00B0, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'NEGSTAT2'                       => self::ObjectField['END'] + 0x00B1, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'NEGSTAT3'                       => self::ObjectField['END'] + 0x00B2, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'NEGSTAT4'                       => self::ObjectField['END'] + 0x00B3, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        // 'RESISTANCES'                    => self::ObjectField['END'] + 0x00B4, #Size:7,Type:INT,Flags:PRIVATE,OWNER_ONLY,UNK3
        'RESISTANCE_NORMAL'              => self::ObjectField['END'] + 0x00B4 + self::Schools['SPELL_SCHOOL_NORMAL'], #armor
        'RESISTANCE_HOLY'                => self::ObjectField['END'] + 0x00B4 + self::Schools['SPELL_SCHOOL_HOLY'],
        'RESISTANCE_FIRE'                => self::ObjectField['END'] + 0x00B4 + self::Schools['SPELL_SCHOOL_FIRE'],
        'RESISTANCE_NATURE'              => self::ObjectField['END'] + 0x00B4 + self::Schools['SPELL_SCHOOL_NATURE'],
        'RESISTANCE_FROST'               => self::ObjectField['END'] + 0x00B4 + self::Schools['SPELL_SCHOOL_FROST'],
        'RESISTANCE_SHADOW'              => self::ObjectField['END'] + 0x00B4 + self::Schools['SPELL_SCHOOL_SHADOW'],
        'RESISTANCE_ARCANE'              => self::ObjectField['END'] + 0x00B4 + self::Schools['SPELL_SCHOOL_ARCANE'],
        'RESISTANCE_NORMAL_BUFF_MOD_POS' => self::ObjectField['END'] + 0x00BB + self::Schools['SPELL_SCHOOL_NORMAL'], #always0?
        'RESISTANCE_HOLY_BUFF_MOD_POS'   => self::ObjectField['END'] + 0x00BB + self::Schools['SPELL_SCHOOL_HOLY'], #always0?
        'RESISTANCE_FIRE_BUFF_MOD_POS'   => self::ObjectField['END'] + 0x00BB + self::Schools['SPELL_SCHOOL_FIRE'],
        'RESISTANCE_NATURE_BUFF_MOD_POS' => self::ObjectField['END'] + 0x00BB + self::Schools['SPELL_SCHOOL_NATURE'],
        'RESISTANCE_FROST_BUFF_MOD_POS'  => self::ObjectField['END'] + 0x00BB + self::Schools['SPELL_SCHOOL_FROST'],
        'RESISTANCE_SHADOW_BUFF_MOD_POS' => self::ObjectField['END'] + 0x00BB + self::Schools['SPELL_SCHOOL_SHADOW'],
        'RESISTANCE_ARCANE_BUFF_MOD_POS' => self::ObjectField['END'] + 0x00BB + self::Schools['SPELL_SCHOOL_ARCANE'],
        'RESISTANCE_NORMAL_BUFF_MOD_NEG' => self::ObjectField['END'] + 0x00C2 + self::Schools['SPELL_SCHOOL_NORMAL'], #always0?
        'RESISTANCE_HOLY_BUFF_MOD_NEG'   => self::ObjectField['END'] + 0x00C2 + self::Schools['SPELL_SCHOOL_HOLY'], #always0?
        'RESISTANCE_FIRE_BUFF_MOD_NEG'   => self::ObjectField['END'] + 0x00C2 + self::Schools['SPELL_SCHOOL_FIRE'],
        'RESISTANCE_NATURE_BUFF_MOD_NEG' => self::ObjectField['END'] + 0x00C2 + self::Schools['SPELL_SCHOOL_NATURE'],
        'RESISTANCE_FROST_BUFF_MOD_NEG'  => self::ObjectField['END'] + 0x00C2 + self::Schools['SPELL_SCHOOL_FROST'],
        'RESISTANCE_SHADOW_BUFF_MOD_NEG' => self::ObjectField['END'] + 0x00C2 + self::Schools['SPELL_SCHOOL_SHADOW'],
        'RESISTANCE_ARCANE_BUFF_MOD_NEG' => self::ObjectField['END'] + 0x00C2 + self::Schools['SPELL_SCHOOL_ARCANE'],
        'BASE_MANA'                      => self::ObjectField['END'] + 0x00C9, #Size:1,Type:INT,Flags:PUBLIC
        'BASE_HEALTH'                    => self::ObjectField['END'] + 0x00CA, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'BYTES_2'                        => self::ObjectField['END'] + 0x00CB, #Size:1,Type:BYTES,Flags:PUBLIC
        'ATTACK_POWER'                   => self::ObjectField['END'] + 0x00CC, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'ATTACK_POWER_MODS'              => self::ObjectField['END'] + 0x00CD, #Size:1,Type:TWO_SHORT,Flags:PRIVATE,OWNER_ONLY
        'ATTACK_POWER_MULTIPLIER'        => self::ObjectField['END'] + 0x00CE, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY
        'RANGED_ATTACK_POWER'            => self::ObjectField['END'] + 0x00CF, #Size:1,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'RANGED_ATTACK_POWER_MODS'       => self::ObjectField['END'] + 0x00D0, #Size:1,Type:TWO_SHORT,Flags:PRIVATE,OWNER_ONLY
        'RANGED_ATTACK_POWER_MULTIPLIER' => self::ObjectField['END'] + 0x00D1, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY
        'MINRANGEDDAMAGE'                => self::ObjectField['END'] + 0x00D2, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY
        'MAXRANGEDDAMAGE'                => self::ObjectField['END'] + 0x00D3, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY
        'POWER_COST_MODIFIER'            => self::ObjectField['END'] + 0x00D4, #Size:7,Type:INT,Flags:PRIVATE,OWNER_ONLY
        'POWER_COST_MULTIPLIER'          => self::ObjectField['END'] + 0x00DB, #Size:7,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY
        'MAXHEALTHMODIFIER'              => self::ObjectField['END'] + 0x00E2, #Size:1,Type:FLOAT,Flags:PRIVATE,OWNER_ONLY
        'PADDING'                        => self::ObjectField['END'] + 0x00E3, #Size:1,Type:INT,Flags:NONE
        'END'                            => self::ObjectField['END'] + 0x00E4,
    ];

    const PlayerField = [
        'DUEL_ARBITER'                   => self::UnitField['END'] + 0x0000, #Size:2,Type:LONG,Flags:PUBLIC
        'FLAGS'                          => self::UnitField['END'] + 0x0002, #Size:1,Type:INT,Flags:PUBLIC
        'GUILDID'                        => self::UnitField['END'] + 0x0003, #Size:1,Type:INT,Flags:PUBLIC
        'GUILDRANK'                      => self::UnitField['END'] + 0x0004, #Size:1,Type:INT,Flags:PUBLIC
        'BYTES_1'                        => self::UnitField['END'] + 0x0005, #Size:1,Type:BYTES,Flags:PUBLIC
        'BYTES_2'                        => self::UnitField['END'] + 0x0006, #Size:1,Type:BYTES,Flags:PUBLIC
        'BYTES_3'                        => self::UnitField['END'] + 0x0007, #Size:1,Type:BYTES,Flags:PUBLIC
        'DUEL_TEAM'                      => self::UnitField['END'] + 0x0008, #Size:1,Type:INT,Flags:PUBLIC
        'GUILD_TIMESTAMP'                => self::UnitField['END'] + 0x0009, #Size:1,Type:INT,Flags:PUBLIC
        'QUEST_LOG_1_1'                  => self::UnitField['END'] + 0x000A, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_1_2'                  => self::UnitField['END'] + 0x000B, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_1_3'                  => self::UnitField['END'] + 0x000C, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_1_4'                  => self::UnitField['END'] + 0x000D, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_2_1'                  => self::UnitField['END'] + 0x000E, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_2_2'                  => self::UnitField['END'] + 0x000F, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_2_3'                  => self::UnitField['END'] + 0x0010, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_2_4'                  => self::UnitField['END'] + 0x0011, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_3_1'                  => self::UnitField['END'] + 0x0012, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_3_2'                  => self::UnitField['END'] + 0x0013, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_3_3'                  => self::UnitField['END'] + 0x0014, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_3_4'                  => self::UnitField['END'] + 0x0015, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_4_1'                  => self::UnitField['END'] + 0x0016, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_4_2'                  => self::UnitField['END'] + 0x0017, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_4_3'                  => self::UnitField['END'] + 0x0018, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_4_4'                  => self::UnitField['END'] + 0x0019, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_5_1'                  => self::UnitField['END'] + 0x001A, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_5_2'                  => self::UnitField['END'] + 0x001B, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_5_3'                  => self::UnitField['END'] + 0x001C, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_5_4'                  => self::UnitField['END'] + 0x001D, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_6_1'                  => self::UnitField['END'] + 0x001E, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_6_2'                  => self::UnitField['END'] + 0x001F, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_6_3'                  => self::UnitField['END'] + 0x0020, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_6_4'                  => self::UnitField['END'] + 0x0021, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_7_1'                  => self::UnitField['END'] + 0x0022, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_7_2'                  => self::UnitField['END'] + 0x0023, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_7_3'                  => self::UnitField['END'] + 0x0024, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_7_4'                  => self::UnitField['END'] + 0x0025, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_8_1'                  => self::UnitField['END'] + 0x0026, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_8_2'                  => self::UnitField['END'] + 0x0027, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_8_3'                  => self::UnitField['END'] + 0x0028, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_8_4'                  => self::UnitField['END'] + 0x0029, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_9_1'                  => self::UnitField['END'] + 0x002A, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_9_2'                  => self::UnitField['END'] + 0x002B, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_9_3'                  => self::UnitField['END'] + 0x002C, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_9_4'                  => self::UnitField['END'] + 0x002D, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_10_1'                 => self::UnitField['END'] + 0x002E, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_10_2'                 => self::UnitField['END'] + 0x002F, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_10_3'                 => self::UnitField['END'] + 0x0030, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_10_4'                 => self::UnitField['END'] + 0x0031, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_11_1'                 => self::UnitField['END'] + 0x0032, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_11_2'                 => self::UnitField['END'] + 0x0033, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_11_3'                 => self::UnitField['END'] + 0x0034, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_11_4'                 => self::UnitField['END'] + 0x0035, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_12_1'                 => self::UnitField['END'] + 0x0036, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_12_2'                 => self::UnitField['END'] + 0x0037, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_12_3'                 => self::UnitField['END'] + 0x0038, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_12_4'                 => self::UnitField['END'] + 0x0039, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_13_1'                 => self::UnitField['END'] + 0x003A, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_13_2'                 => self::UnitField['END'] + 0x003B, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_13_3'                 => self::UnitField['END'] + 0x003C, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_13_4'                 => self::UnitField['END'] + 0x003D, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_14_1'                 => self::UnitField['END'] + 0x003E, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_14_2'                 => self::UnitField['END'] + 0x003F, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_14_3'                 => self::UnitField['END'] + 0x0040, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_14_4'                 => self::UnitField['END'] + 0x0041, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_15_1'                 => self::UnitField['END'] + 0x0042, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_15_2'                 => self::UnitField['END'] + 0x0043, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_15_3'                 => self::UnitField['END'] + 0x0044, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_15_4'                 => self::UnitField['END'] + 0x0045, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_16_1'                 => self::UnitField['END'] + 0x0046, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_16_2'                 => self::UnitField['END'] + 0x0047, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_16_3'                 => self::UnitField['END'] + 0x0048, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_16_4'                 => self::UnitField['END'] + 0x0049, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_17_1'                 => self::UnitField['END'] + 0x004A, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_17_2'                 => self::UnitField['END'] + 0x004B, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_17_3'                 => self::UnitField['END'] + 0x004C, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_17_4'                 => self::UnitField['END'] + 0x004D, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_18_1'                 => self::UnitField['END'] + 0x004E, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_18_2'                 => self::UnitField['END'] + 0x004F, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_18_3'                 => self::UnitField['END'] + 0x0050, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_18_4'                 => self::UnitField['END'] + 0x0051, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_19_1'                 => self::UnitField['END'] + 0x0052, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_19_2'                 => self::UnitField['END'] + 0x0053, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_19_3'                 => self::UnitField['END'] + 0x0054, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_19_4'                 => self::UnitField['END'] + 0x0055, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_20_1'                 => self::UnitField['END'] + 0x0056, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_20_2'                 => self::UnitField['END'] + 0x0057, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_20_3'                 => self::UnitField['END'] + 0x0058, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_20_4'                 => self::UnitField['END'] + 0x0059, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_21_1'                 => self::UnitField['END'] + 0x005A, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_21_2'                 => self::UnitField['END'] + 0x005B, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_21_3'                 => self::UnitField['END'] + 0x005C, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_21_4'                 => self::UnitField['END'] + 0x005D, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_22_1'                 => self::UnitField['END'] + 0x005E, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_22_2'                 => self::UnitField['END'] + 0x005F, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_22_3'                 => self::UnitField['END'] + 0x0060, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_22_4'                 => self::UnitField['END'] + 0x0061, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_23_1'                 => self::UnitField['END'] + 0x0062, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_23_2'                 => self::UnitField['END'] + 0x0063, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_23_3'                 => self::UnitField['END'] + 0x0064, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_23_4'                 => self::UnitField['END'] + 0x0065, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_24_1'                 => self::UnitField['END'] + 0x0066, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_24_2'                 => self::UnitField['END'] + 0x0067, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_24_3'                 => self::UnitField['END'] + 0x0068, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_24_4'                 => self::UnitField['END'] + 0x0069, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_25_1'                 => self::UnitField['END'] + 0x006A, #Size:1,Type:INT,Flags:GROUP_ONLY
        'QUEST_LOG_25_2'                 => self::UnitField['END'] + 0x006B, #Size:1,Type:INT,Flags:PRIVATE
        'QUEST_LOG_25_3'                 => self::UnitField['END'] + 0x006C, #Size:1,Type:BYTES,Flags:PRIVATE
        'QUEST_LOG_25_4'                 => self::UnitField['END'] + 0x006D, #Size:1,Type:INT,Flags:PRIVATE
        'VISIBLE_ITEM_1_CREATOR'         => self::UnitField['END'] + 0x006E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_1_0'               => self::UnitField['END'] + 0x0070, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_1_PROPERTIES'      => self::UnitField['END'] + 0x007C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_1_PAD'             => self::UnitField['END'] + 0x007D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_2_CREATOR'         => self::UnitField['END'] + 0x007E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_2_0'               => self::UnitField['END'] + 0x0080, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_2_PROPERTIES'      => self::UnitField['END'] + 0x008C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_2_PAD'             => self::UnitField['END'] + 0x008D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_3_CREATOR'         => self::UnitField['END'] + 0x008E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_3_0'               => self::UnitField['END'] + 0x0090, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_3_PROPERTIES'      => self::UnitField['END'] + 0x009C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_3_PAD'             => self::UnitField['END'] + 0x009D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_4_CREATOR'         => self::UnitField['END'] + 0x009E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_4_0'               => self::UnitField['END'] + 0x00A0, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_4_PROPERTIES'      => self::UnitField['END'] + 0x00AC, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_4_PAD'             => self::UnitField['END'] + 0x00AD, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_5_CREATOR'         => self::UnitField['END'] + 0x00AE, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_5_0'               => self::UnitField['END'] + 0x00B0, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_5_PROPERTIES'      => self::UnitField['END'] + 0x00BC, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_5_PAD'             => self::UnitField['END'] + 0x00BD, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_6_CREATOR'         => self::UnitField['END'] + 0x00BE, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_6_0'               => self::UnitField['END'] + 0x00C0, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_6_PROPERTIES'      => self::UnitField['END'] + 0x00CC, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_6_PAD'             => self::UnitField['END'] + 0x00CD, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_7_CREATOR'         => self::UnitField['END'] + 0x00CE, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_7_0'               => self::UnitField['END'] + 0x00D0, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_7_PROPERTIES'      => self::UnitField['END'] + 0x00DC, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_7_PAD'             => self::UnitField['END'] + 0x00DD, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_8_CREATOR'         => self::UnitField['END'] + 0x00DE, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_8_0'               => self::UnitField['END'] + 0x00E0, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_8_PROPERTIES'      => self::UnitField['END'] + 0x00EC, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_8_PAD'             => self::UnitField['END'] + 0x00ED, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_9_CREATOR'         => self::UnitField['END'] + 0x00EE, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_9_0'               => self::UnitField['END'] + 0x00F0, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_9_PROPERTIES'      => self::UnitField['END'] + 0x00FC, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_9_PAD'             => self::UnitField['END'] + 0x00FD, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_10_CREATOR'        => self::UnitField['END'] + 0x00FE, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_10_0'              => self::UnitField['END'] + 0x0100, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_10_PROPERTIES'     => self::UnitField['END'] + 0x010C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_10_PAD'            => self::UnitField['END'] + 0x010D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_11_CREATOR'        => self::UnitField['END'] + 0x010E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_11_0'              => self::UnitField['END'] + 0x0110, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_11_PROPERTIES'     => self::UnitField['END'] + 0x011C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_11_PAD'            => self::UnitField['END'] + 0x011D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_12_CREATOR'        => self::UnitField['END'] + 0x011E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_12_0'              => self::UnitField['END'] + 0x0120, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_12_PROPERTIES'     => self::UnitField['END'] + 0x012C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_12_PAD'            => self::UnitField['END'] + 0x012D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_13_CREATOR'        => self::UnitField['END'] + 0x012E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_13_0'              => self::UnitField['END'] + 0x0130, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_13_PROPERTIES'     => self::UnitField['END'] + 0x013C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_13_PAD'            => self::UnitField['END'] + 0x013D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_14_CREATOR'        => self::UnitField['END'] + 0x013E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_14_0'              => self::UnitField['END'] + 0x0140, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_14_PROPERTIES'     => self::UnitField['END'] + 0x014C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_14_PAD'            => self::UnitField['END'] + 0x014D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_15_CREATOR'        => self::UnitField['END'] + 0x014E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_15_0'              => self::UnitField['END'] + 0x0150, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_15_PROPERTIES'     => self::UnitField['END'] + 0x015C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_15_PAD'            => self::UnitField['END'] + 0x015D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_16_CREATOR'        => self::UnitField['END'] + 0x015E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_16_0'              => self::UnitField['END'] + 0x0160, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_16_PROPERTIES'     => self::UnitField['END'] + 0x016C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_16_PAD'            => self::UnitField['END'] + 0x016D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_17_CREATOR'        => self::UnitField['END'] + 0x016E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_17_0'              => self::UnitField['END'] + 0x0170, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_17_PROPERTIES'     => self::UnitField['END'] + 0x017C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_17_PAD'            => self::UnitField['END'] + 0x017D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_18_CREATOR'        => self::UnitField['END'] + 0x017E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_18_0'              => self::UnitField['END'] + 0x0180, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_18_PROPERTIES'     => self::UnitField['END'] + 0x018C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_18_PAD'            => self::UnitField['END'] + 0x018D, #Size:1,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_19_CREATOR'        => self::UnitField['END'] + 0x018E, #Size:2,Type:LONG,Flags:PUBLIC
        'VISIBLE_ITEM_19_0'              => self::UnitField['END'] + 0x0190, #Size:12,Type:INT,Flags:PUBLIC
        'VISIBLE_ITEM_19_PROPERTIES'     => self::UnitField['END'] + 0x019C, #Size:1,Type:TWO_SHORT,Flags:PUBLIC
        'VISIBLE_ITEM_19_PAD'            => self::UnitField['END'] + 0x019D, #Size:1,Type:INT,Flags:PUBLIC
        'CHOSEN_TITLE'                   => self::UnitField['END'] + 0x019E, #Size:1,Type:INT,Flags:PUBLIC
        'PAD_0'                          => self::UnitField['END'] + 0x019F, #Size:1,Type:INT,Flags:NONE
        'INV_SLOT_HEAD'                  => self::UnitField['END'] + 0x01A0, #Size:46,Type:LONG,Flags:PRIVATE
        'INV_SLOT_NECK'                  => self::UnitField['END'] + 0x01A0 + 2,
        'INV_SLOT_SHOULDERS'             => self::UnitField['END'] + 0x01A0 + 4,
        'INV_SLOT_BODY'                  => self::UnitField['END'] + 0x01A0 + 6,
        'INV_SLOT_CHEST'                 => self::UnitField['END'] + 0x01A0 + 8,
        'INV_SLOT_WAIST'                 => self::UnitField['END'] + 0x01A0 + 10,
        'INV_SLOT_LEGS'                  => self::UnitField['END'] + 0x01A0 + 12,
        'INV_SLOT_FEET'                  => self::UnitField['END'] + 0x01A0 + 14,
        'INV_SLOT_WRISTS'                => self::UnitField['END'] + 0x01A0 + 16,
        'INV_SLOT_HANDS'                 => self::UnitField['END'] + 0x01A0 + 18,
        'INV_SLOT_FINGER1'               => self::UnitField['END'] + 0x01A0 + 20,
        'INV_SLOT_FINGER2'               => self::UnitField['END'] + 0x01A0 + 22,
        'INV_SLOT_TRINKET1'              => self::UnitField['END'] + 0x01A0 + 24,
        'INV_SLOT_TRINKET2'              => self::UnitField['END'] + 0x01A0 + 26,
        'INV_SLOT_BACK'                  => self::UnitField['END'] + 0x01A0 + 28,
        'INV_SLOT_MAINHAND'              => self::UnitField['END'] + 0x01A0 + 30,
        'INV_SLOT_OFFHAND'               => self::UnitField['END'] + 0x01A0 + 32,
        'INV_SLOT_RANGED'                => self::UnitField['END'] + 0x01A0 + 34,
        'INV_SLOT_TABARD'                => self::UnitField['END'] + 0x01A0 + 36,
        'INV_SLOT_BAG1'                  => self::UnitField['END'] + 0x01A0 + 38,
        'INV_SLOT_BAG2'                  => self::UnitField['END'] + 0x01A0 + 40,
        'INV_SLOT_BAG3'                  => self::UnitField['END'] + 0x01A0 + 42,
        'INV_SLOT_BAG4'                  => self::UnitField['END'] + 0x01A0 + 44,
        'PACK_SLOT_1'                    => self::UnitField['END'] + 0x01CE, #Size:32,Type:LONG,Flags:PRIVATE
        'BANK_SLOT_1'                    => self::UnitField['END'] + 0x01EE, #Size:56,Type:LONG,Flags:PRIVATE
        'BANKBAG_SLOT_1'                 => self::UnitField['END'] + 0x0226, #Size:14,Type:LONG,Flags:PRIVATE
        'VENDORBUYBACK_SLOT_1'           => self::UnitField['END'] + 0x0234, #Size:24,Type:LONG,Flags:PRIVATE
        'KEYRING_SLOT_1'                 => self::UnitField['END'] + 0x024C, #Size:64,Type:LONG,Flags:PRIVATE
        'VANITYPET_SLOT_1'               => self::UnitField['END'] + 0x028C, #Size:36,Type:LONG,Flags:PRIVATE
        'FARSIGHT'                       => self::UnitField['END'] + 0x02B0, #Size:2,Type:LONG,Flags:PRIVATE
        '_FIELD_KNOWN_TITLES'            => self::UnitField['END'] + 0x02B2, #Size:2,Type:LONG,Flags:PRIVATE
        'XP'                             => self::UnitField['END'] + 0x02B4, #Size:1,Type:INT,Flags:PRIVATE
        'NEXT_LEVEL_XP'                  => self::UnitField['END'] + 0x02B5, #Size:1,Type:INT,Flags:PRIVATE
        'SKILL_INFO_1_ID'                => self::UnitField['END'] + 0x02B6, #Size:384,Type:TWO_SHORT,Flags:PRIVATE
        'SKILL_INFO_1_LEVEL'             => self::UnitField['END'] + 0x02B7,
        'SKILL_INFO_1_STAT_LEVEL'        => self::UnitField['END'] + 0x02B8,
        'CHARACTER_POINTS1'              => self::UnitField['END'] + 0x0436, #Size:1,Type:INT,Flags:PRIVATE
        'CHARACTER_POINTS2'              => self::UnitField['END'] + 0x0437, #Size:1,Type:INT,Flags:PRIVATE
        'TRACK_CREATURES'                => self::UnitField['END'] + 0x0438, #Size:1,Type:INT,Flags:PRIVATE
        'TRACK_RESOURCES'                => self::UnitField['END'] + 0x0439, #Size:1,Type:INT,Flags:PRIVATE
        'BLOCK_PERCENTAGE'               => self::UnitField['END'] + 0x043A, #Size:1,Type:FLOAT,Flags:PRIVATE
        'DODGE_PERCENTAGE'               => self::UnitField['END'] + 0x043B, #Size:1,Type:FLOAT,Flags:PRIVATE
        'PARRY_PERCENTAGE'               => self::UnitField['END'] + 0x043C, #Size:1,Type:FLOAT,Flags:PRIVATE
        'EXPERTISE'                      => self::UnitField['END'] + 0x043D, #Size:1,Type:INT,Flags:PRIVATE
        'OFFHAND_EXPERTISE'              => self::UnitField['END'] + 0x043E, #Size:1,Type:INT,Flags:PRIVATE
        'CRIT_PERCENTAGE'                => self::UnitField['END'] + 0x043F, #Size:1,Type:FLOAT,Flags:PRIVATE
        'RANGED_CRIT_PERCENTAGE'         => self::UnitField['END'] + 0x0440, #Size:1,Type:FLOAT,Flags:PRIVATE
        'OFFHAND_CRIT_PERCENTAGE'        => self::UnitField['END'] + 0x0441, #Size:1,Type:FLOAT,Flags:PRIVATE
        '#SPELL_CRIT_PERCENTAGE1'        => self::UnitField['END'] + 0x0442, #Size:7,Type:FLOAT,Flags:PRIVATE
        'SPELL_CRIT_NORMAL_PERCENTAGE'   => self::UnitField['END'] + 0x0442 + self::Schools['SPELL_SCHOOL_NORMAL'], #always0?
        'SPELL_CRIT_HOLY_PERCENTAGE'     => self::UnitField['END'] + 0x0442 + self::Schools['SPELL_SCHOOL_HOLY'],
        'SPELL_CRIT_FIRE_PERCENTAGE'     => self::UnitField['END'] + 0x0442 + self::Schools['SPELL_SCHOOL_FIRE'],
        'SPELL_CRIT_NATURE_PERCENTAGE'   => self::UnitField['END'] + 0x0442 + self::Schools['SPELL_SCHOOL_NATURE'],
        'SPELL_CRIT_FROST_PERCENTAGE'    => self::UnitField['END'] + 0x0442 + self::Schools['SPELL_SCHOOL_FROST'],
        'SPELL_CRIT_SHADOW_PERCENTAGE'   => self::UnitField['END'] + 0x0442 + self::Schools['SPELL_SCHOOL_SHADOW'],
        'SPELL_CRIT_ARCANE_PERCENTAGE'   => self::UnitField['END'] + 0x0442 + self::Schools['SPELL_SCHOOL_ARCANE'],
        'SHIELD_BLOCK'                   => self::UnitField['END'] + 0x0449, #Size:1,Type:INT,Flags:PRIVATE
        'EXPLORED_ZONES_1'               => self::UnitField['END'] + 0x044A, #Size:128,Type:BYTES,Flags:PRIVATE
        'REST_STATE_EXPERIENCE'          => self::UnitField['END'] + 0x04CA, #Size:1,Type:INT,Flags:PRIVATE
        'COINAGE'                        => self::UnitField['END'] + 0x04CB, #Size:1,Type:INT,Flags:PRIVATE
        'MOD_DAMAGE_DONE_POS'            => self::UnitField['END'] + 0x04CC, #Size:7,Type:INT,Flags:PRIVATE
        #'MOD_DAMAGE_NORMAL_DONE_POS'=>self::UnitField['END']+0x04CC+self::Schools['SPELL_SCHOOL_NORMAL'],
        #'MOD_DAMAGE_HOLY_DONE_POS'=>self::UnitField['END']+0x04CC+self::Schools['SPELL_SCHOOL_HOLY'],
        #'MOD_DAMAGE_FIRE_DONE_POS'=>self::UnitField['END']+0x04CC+self::Schools['SPELL_SCHOOL_FIRE'],
        #'MOD_DAMAGE_NATURE_DONE_POS'=>self::UnitField['END']+0x04CC+self::Schools['SPELL_SCHOOL_NATURE'],
        #'MOD_DAMAGE_FROST_DONE_POS'=>self::UnitField['END']+0x04CC+self::Schools['SPELL_SCHOOL_FROST'],
        #'MOD_DAMAGE_SHADOW_DONE_POS'=>self::UnitField['END']+0x04CC+self::Schools['SPELL_SCHOOL_SHADOW'],
        #'MOD_DAMAGE_ARCANE_DONE_POS'=>self::UnitField['END']+0x04CC+self::Schools['SPELL_SCHOOL_ARCANE'],
        'MOD_DAMAGE_DONE_NEG'            => self::UnitField['END'] + 0x04D3, #Size:7,Type:INT,Flags:PRIVATE
        #'MOD_DAMAGE_NORMAL_DONE_NEG'=>self::UnitField['END']+0x04D3+self::Schools['SPELL_SCHOOL_NORMAL'],
        #'MOD_DAMAGE_HOLY_DONE_NEG'=>self::UnitField['END']+0x04D3+self::Schools['SPELL_SCHOOL_HOLY'],
        #'MOD_DAMAGE_FIRE_DONE_NEG'=>self::UnitField['END']+0x04D3+self::Schools['SPELL_SCHOOL_FIRE'],
        #'MOD_DAMAGE_NATURE_DONE_NEG'=>self::UnitField['END']+0x04D3+self::Schools['SPELL_SCHOOL_NATURE'],
        #'MOD_DAMAGE_FROST_DONE_NEG'=>self::UnitField['END']+0x04D3+self::Schools['SPELL_SCHOOL_FROST'],
        #'MOD_DAMAGE_SHADOW_DONE_NEG'=>self::UnitField['END']+0x04D3+self::Schools['SPELL_SCHOOL_SHADOW'],
        #'MOD_DAMAGE_ARCANE_DONE_NEG'=>self::UnitField['END']+0x04D3+self::Schools['SPELL_SCHOOL_ARCANE'],
        'MOD_DAMAGE_DONE_PCT'            => self::UnitField['END'] + 0x04DA, #Size:7,Type:INT,Flags:PRIVATE
        'MOD_DAMAGE_NORMAL_DONE_PCT'     => self::UnitField['END'] + 0x04DA + self::Schools['SPELL_SCHOOL_NORMAL'],
        'MOD_DAMAGE_HOLY_DONE_PCT'       => self::UnitField['END'] + 0x04DA + self::Schools['SPELL_SCHOOL_HOLY'],
        'MOD_DAMAGE_FIRE_DONE_PCT'       => self::UnitField['END'] + 0x04DA + self::Schools['SPELL_SCHOOL_FIRE'],
        'MOD_DAMAGE_NATURE_DONE_PCT'     => self::UnitField['END'] + 0x04DA + self::Schools['SPELL_SCHOOL_NATURE'],
        'MOD_DAMAGE_FROST_DONE_PCT'      => self::UnitField['END'] + 0x04DA + self::Schools['SPELL_SCHOOL_FROST'],
        'MOD_DAMAGE_SHADOW_DONE_PCT'     => self::UnitField['END'] + 0x04DA + self::Schools['SPELL_SCHOOL_SHADOW'],
        'MOD_DAMAGE_ARCANE_DONE_PCT'     => self::UnitField['END'] + 0x04DA + self::Schools['SPELL_SCHOOL_ARCANE'],
        'MOD_HEALING_DONE_POS'           => self::UnitField['END'] + 0x04E1, #Size:1,Type:INT,Flags:PRIVATE
        'MOD_TARGET_RESISTANCE'          => self::UnitField['END'] + 0x04E2, #Size:1,Type:INT,Flags:PRIVATE
        'MOD_TARGET_PHYSICAL_RESISTANCE' => self::UnitField['END'] + 0x04E3, #Size:1,Type:INT,Flags:PRIVATE
        'BYTES'                          => self::UnitField['END'] + 0x04E4, #Size:1,Type:BYTES,Flags:PRIVATE
        'AMMO_ID'                        => self::UnitField['END'] + 0x04E5, #Size:1,Type:INT,Flags:PRIVATE
        'SELF_RES_SPELL'                 => self::UnitField['END'] + 0x04E6, #Size:1,Type:INT,Flags:PRIVATE
        'PVP_MEDALS'                     => self::UnitField['END'] + 0x04E7, #Size:1,Type:INT,Flags:PRIVATE
        'BUYBACK_PRICE_1'                => self::UnitField['END'] + 0x04E8, #Size:12,Type:INT,Flags:PRIVATE
        'BUYBACK_TIMESTAMP_1'            => self::UnitField['END'] + 0x04F4, #Size:12,Type:INT,Flags:PRIVATE
        'KILLS'                          => self::UnitField['END'] + 0x0500, #Size:1,Type:TWO_SHORT,Flags:PRIVATE
        'TODAY_CONTRIBUTION'             => self::UnitField['END'] + 0x0501, #Size:1,Type:INT,Flags:PRIVATE
        'YESTERDAY_CONTRIBUTION'         => self::UnitField['END'] + 0x0502, #Size:1,Type:INT,Flags:PRIVATE
        'LIFETIME_HONORABLE_KILLS'       => self::UnitField['END'] + 0x0503, #Size:1,Type:INT,Flags:PRIVATE
        'BYTES2'                         => self::UnitField['END'] + 0x0504, #Size:1,Type:BYTES,Flags:PRIVATE
        'WATCHED_FACTION_INDEX'          => self::UnitField['END'] + 0x0505, #Size:1,Type:INT,Flags:PRIVATE
        'COMBAT_RATING_1'                => self::UnitField['END'] + 0x0506, #Size:24,Type:INT,Flags:PRIVATE
        'ARENA_TEAM_INFO_1_1'            => self::UnitField['END'] + 0x051E, #Size:18,Type:INT,Flags:PRIVATE
        'HONOR_CURRENCY'                 => self::UnitField['END'] + 0x0530, #Size:1,Type:INT,Flags:PRIVATE
        'ARENA_CURRENCY'                 => self::UnitField['END'] + 0x0531, #Size:1,Type:INT,Flags:PRIVATE
        'MOD_MANA_REGEN'                 => self::UnitField['END'] + 0x0532, #Size:1,Type:FLOAT,Flags:PRIVATE
        'MOD_MANA_REGEN_INTERRUPT'       => self::UnitField['END'] + 0x0533, #Size:1,Type:FLOAT,Flags:PRIVATE
        'MAX_LEVEL'                      => self::UnitField['END'] + 0x0534, #Size:1,Type:INT,Flags:PRIVATE
        'DAILY_QUESTS_1'                 => self::UnitField['END'] + 0x0535, #Size:25,Type:INT,Flags:PRIVATE
        'END'                            => self::UnitField['END'] + 0x054E,
    ];

}
